#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 三 四
bspc monitor HDMI-0 -d 一 二
bspc monitor DP-4 -d 五 六

bspc config border_width         0
bspc config window_gap          20 #12
bspc config border_radius       15   #15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config -m DP-2 top_padding  50
bspc config pointer_motion_interval 40

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr

~/.config/polybar/launch.sh

xrandr --output DP-2 --primary --mode 1920x1080 --rate 144.00
xrandr --output HDMI-0 --mode 1680x1050 --rate 60.00 --left-of DP-2
xrandr --output DP-4 --mode 1680x1050 --rate 60.00 --right-of DP-2

feh --bg-fill ~/images/wallpaperflare-cropped
#feh --bg-fill ~/images/power.png

xinput --set-prop 14 285 0.01
xinput disable 17
xinput disable 18

picom --config ~/.config/picom/picom.conf
# picom --corner-radius 25

uim-xim
uim-toolbar-gtk3

## Add this to your wm startup file.

# Terminate already running bar instances
#killall -q polybar

## Wait until the processes have been shut down
#while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

## Launch
#my_laptop_external_monitor=$(xrandr --query | grep 'VGA1')
#if [[ $my_laptop_external_monitor = VGA1\ connected* ]]; then
#else
#fi

#polybar primary -c ~/.config/polybar/config.ini &
#sleep 1 &&
#polybar music -c ~/.config/polybar/config.ini &
#polybar secondary -c ~/.config/polybar/config.ini &
